/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#002a58",
        "on-secondary": "#ffffff",
        "tertiary": "#002b55",
        "on-background": "#191c1d",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dbe4ed",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#c3c6d2",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#a9c7ff",
        "outline": "#737781",
        "on-error": "#ffffff",
        "primary-container": "#004080",
        "tertiary-container": "#1f416d",
        "background": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "on-primary-fixed-variant": "#0e4686",
        "on-primary-container": "#83aef5",
        "surface": "#f8f9fa",
        "secondary": "#575f67",
        "on-primary-fixed": "#001b3d",
        "inverse-primary": "#a9c7ff",
        "on-secondary-fixed-variant": "#3f484f",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#305ea0",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bfc8d0",
        "tertiary-fixed-dim": "#a8c8fc",
        "inverse-on-surface": "#f0f1f2",
        "on-error-container": "#93000a",
        "secondary-container": "#d8e1ea",
        "surface-bright": "#f8f9fa",
        "error-container": "#ffdad6",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#424750",
        "on-tertiary-fixed-variant": "#264774",
        "on-secondary-fixed": "#141d23",
        "on-tertiary-container": "#8eaee0",
        "on-secondary-container": "#5b646b",
        "surface-container-high": "#e7e8e9",
        "primary-fixed": "#d6e3ff",
        "tertiary-fixed": "#d5e3ff",
        "on-tertiary-fixed": "#001c3b",
        "surface-dim": "#d9dadb",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        gutter: "24px",
        lg: "48px",
        sm: "16px",
        margin: "auto",
        md: "24px",
        xl: "80px",
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
